### ISSUE TITLE
Can not activate plugin. Parse error: syntax error, unexpected

### ISSUE THREAD

**Issue by joelworsham** [brashrebel/client-dash#104]
https://wordpress.org/support/topic/can-not-activate-plugin-parse-error-syntax-error-unexpected?replies=10

**Comment by brashrebel** [comment]
What is the plan here? Pushing out a patch?

Also, just as a note:
wp.org != wordpress.org
w.org == wordpress.org

**Comment by joelworsham** [comment]
says who?

And yes, it's already been pushed to its own branch. It just needs to be merged into dev, then pushed as a new release into master, and then into SVN. Just figured I'd wait until tomorrow

**Comment by brashrebel** [comment]
Roger.
